extends: default

rules:
  line-length: disable
  document-start: disable
  truthy:
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  indentation:
    spaces: 2
    indent-sequences: consistent