name: Shell Script Linting

on:
  push:
    branches: [main]
    paths:
      - 'scripts/**.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    branches: [main]
    paths:
      - 'scripts/**.sh'
      - '.github/workflows/shellcheck.yml'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:stable
    name: ShellCheck
    steps:
      - uses: actions/checkout@v4

      - name: List shell scripts
        id: list-scripts
        run: |
          if [[ -d "./scripts" && $(find ./scripts -name "*.sh" | wc -l) -gt 0 ]]; then
            echo "SHELL_SCRIPTS_EXIST=true" >> $GITHUB_ENV
            find ./scripts -name "*.sh" -type f
          else
            echo "SHELL_SCRIPTS_EXIST=false" >> $GITHUB_ENV
            echo "No shell scripts found in ./scripts directory"
          fi

      - name: Run shellcheck
        if: env.SHELL_SCRIPTS_EXIST == 'true'
        run: |
          echo "Running shellcheck on shell scripts:"
          find ./scripts -name "*.sh" -type f -print0 | xargs -0 shellcheck --severity=warning
