name: Test Docker CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ ci-fixes ]
    paths:
      - '.github/workflows/test-docker-ci.yml'

jobs:
  test-docker-lua:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - lua-version: "5.1"
            container: "nickblah/lua:5.1-luarocks-alpine"
          - lua-version: "5.3"
            container: "nickblah/lua:5.3-luarocks-alpine"
          - lua-version: "5.4"
            container: "nickblah/lua:5.4-luarocks-alpine"
          - lua-version: "luajit"
            container: "nickblah/luajit:luarocks-alpine"
    
    container: ${{ matrix.container }}
    name: Test Docker Lua ${{ matrix.lua-version }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Check Lua version
        run: |
          lua -v || luajit -v
          
      - name: Check LuaRocks
        run: |
          luarocks --version
          luarocks list
          
      - name: Install build dependencies
        run: |
          apk add --no-cache build-base
          
      - name: Install luacheck
        run: |
          luarocks install luacheck
          
      - name: Run Luacheck
        run: |
          luacheck lua/
          
  benchmark-comparison:
    runs-on: ubuntu-latest
    name: Benchmark APT vs Docker
    steps:
      - uses: actions/checkout@v4
      
      - name: Time APT installation
        run: |
          echo "=== APT Installation Benchmark ==="
          START_TIME=$(date +%s)
          sudo apt-get update
          sudo apt-get install -y lua5.4 liblua5.4-dev luarocks
          sudo luarocks install luacheck
          END_TIME=$(date +%s)
          echo "APT installation took: $((END_TIME - START_TIME)) seconds"
          
      - name: Time Docker approach
        run: |
          echo "=== Docker Approach Benchmark ==="
          START_TIME=$(date +%s)
          docker pull nickblah/lua:5.4-luarocks-alpine
          docker run --rm -v $(pwd):/work -w /work nickblah/lua:5.4-luarocks-alpine sh -c "apk add --no-cache build-base && luarocks install luacheck"
          END_TIME=$(date +%s)
          echo "Docker approach took: $((END_TIME - START_TIME)) seconds"