name: Lint YAML

on:
  push:
    branches: [main]
    paths:
      - '**.yml'
      - '**.yaml'
  pull_request:
    branches: [main]
    paths:
      - '**.yml'
      - '**.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest
    container: pipelinecomponents/yamllint:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run yamllint
        run: yamllint .
